# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_reader.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11text_reader.proto\x12\x0btext_reader"\r\n\x0bWordRequest")\n\x0cWordResponse\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0b\n\x03\x65of\x18\x02 \x01(\x08\x32R\n\nTextReader\x12\x44\n\x0bGetNextWord\x12\x18.text_reader.WordRequest\x1a\x19.text_reader.WordResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "text_reader_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_WORDREQUEST"]._serialized_start = 34
    _globals["_WORDREQUEST"]._serialized_end = 47
    _globals["_WORDRESPONSE"]._serialized_start = 49
    _globals["_WORDRESPONSE"]._serialized_end = 90
    _globals["_TEXTREADER"]._serialized_start = 92
    _globals["_TEXTREADER"]._serialized_end = 174
# @@protoc_insertion_point(module_scope)
